-- PUBLIC.FILM_LIKE definition

-- Drop table

-- DROP TABLE PUBLIC.FILM_LIKE;

CREATE TABLE PUBLIC.FILM_LIKE (
	USER_ID INTEGER NOT NULL,
	FILM_ID INTEGER NOT NULL,
	CONSTRAINT FILMS_LIKES_FK PRIMARY KEY (USER_ID,USER_ID),
	CONSTRAINT FILMS_LIKES_PK PRIMARY KEY (USER_ID,FILM_ID),
	CONSTRAINT FILM_LIKE_FK PRIMARY KEY (FILM_ID,FILM_ID)
);
CREATE INDEX FILMS_LIKES_FK_INDEX_6 ON PUBLIC.FILM_LIKE (USER_ID);
CREATE INDEX FILM_LIKE_FK_INDEX_6 ON PUBLIC.FILM_LIKE (FILM_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_6F ON PUBLIC.FILM_LIKE (USER_ID,FILM_ID);


-- PUBLIC.FRIENDS definition

-- Drop table

-- DROP TABLE PUBLIC.FRIENDS;

CREATE TABLE PUBLIC.FRIENDS (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	STATUS CHARACTER(20) NOT NULL,
	CONSTRAINT FRIENDS_FK PRIMARY KEY (USER_ID,USER_ID),
	CONSTRAINT FRIENDS_PK PRIMARY KEY (USER_ID,FRIEND_ID)
);
CREATE INDEX FRIENDS_FK_INDEX_7 ON PUBLIC.FRIENDS (USER_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_56 ON PUBLIC.FRIENDS (USER_ID,FRIEND_ID);


-- PUBLIC.GENRE_FILM definition

-- Drop table

-- DROP TABLE PUBLIC.GENRE_FILM;

CREATE TABLE PUBLIC.GENRE_FILM (
	GENRE_ID INTEGER NOT NULL,
	FILM_ID INTEGER NOT NULL,
	CONSTRAINT GENRE_FILM_PK PRIMARY KEY (FILM_ID,GENRE_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_C ON PUBLIC.GENRE_FILM (GENRE_ID,FILM_ID);


-- PUBLIC.GENRES definition

-- Drop table

-- DROP TABLE PUBLIC.GENRES;

CREATE TABLE PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
	GENRE_NAME VARCHAR_IGNORECASE NOT NULL,
	CONSTRAINT GENRES_PK PRIMARY KEY (GENRE_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_5A ON PUBLIC.GENRES (GENRE_ID);


-- PUBLIC.MPA_RATINGS definition

-- Drop table

-- DROP TABLE PUBLIC.MPA_RATINGS;

CREATE TABLE PUBLIC.MPA_RATINGS (
	RATING_ID INTEGER NOT NULL AUTO_INCREMENT,
	RATING_NAME CHARACTER(7),
	CONSTRAINT MPA_RATINGS_PK PRIMARY KEY (RATING_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_E7 ON PUBLIC.MPA_RATINGS (RATING_ID);


-- PUBLIC.USERS definition

-- Drop table

-- DROP TABLE PUBLIC.USERS;

CREATE TABLE PUBLIC.USERS (
	USER_LOGIN CHARACTER(40) NOT NULL,
	USER_NAME CHARACTER(40) NOT NULL,
	USER_BIRTHDAY TIMESTAMP,
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
	USER_EMAIL CHARACTER(50) NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (USER_ID)
);
CREATE UNIQUE INDEX PRIMARY_KEY_610 ON PUBLIC.USERS (USER_ID);


-- PUBLIC.FILMS definition

-- Drop table

-- DROP TABLE PUBLIC.FILMS;

CREATE TABLE PUBLIC.FILMS (
	FILM_DESCRIPTION CHARACTER(200) NOT NULL,
	FILM_RELEASE_DATE TIMESTAMP NOT NULL,
	FILM_DURATION INTEGER NOT NULL,
	RATING_ID INTEGER NOT NULL,
	FILM_NAME CHARACTER(100) NOT NULL,
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
	CONSTRAINT FILMS_FK PRIMARY KEY (RATING_ID,RATING_ID),
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID),
	CONSTRAINT FILMS_FK FOREIGN KEY (RATING_ID) REFERENCES PUBLIC.MPA_RATINGS(RATING_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE INDEX FILMS_FK_INDEX_3 ON PUBLIC.FILMS (RATING_ID);
CREATE UNIQUE INDEX PRIMARY_KEY_3 ON PUBLIC.FILMS (FILM_ID);